name: flutter_2048
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.1
  flutter_swipe_detector: ^2.0.0
  path_provider: ^2.0.11
  screenshot: ^1.2.3
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  swipedetector: ^1.2.0
  tuple: ^2.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo.png'
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/images/
